version: 1.2
workflows:

  - name: FungalQC
    subclass: WDL
    primaryDescriptorPath: /workflows/FungalQC.wdl

  - name: FungalTree
    subclass: WDL
    primaryDescriptorPath: /workflows/FungalTree.wdl
